
target 'CocoaPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Toast-Swift', '~> 3.0.0'
	pod 'FSCalendar'

  # Pods for CocoaPractice

  target 'CocoaPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPracticeUITests' do
    # Pods for testing
  end

end
